Refactoring.calibration.pixel2world
chalmers-revere/opendlv.core pull request #103
Opened 2017-05-02 20:34 UTC by bjornborg

Note I also added some modification to the make command buildIncremental for compiling the tools as well.

2017-05-07 12:18 UTC, chrberger requested changes

2017-05-07 12:18 UTC, chrberger commented on code/tool/camera-projection/src/cameraprojection.cpp
> +  m_transformationMatrixFileName = "/opt/opendlv.core.configuration/" + m_cameraName + "-pixel2word-matrix.csv";
You should use the relative path of this module (i.e., "./") and make sure that the corresponding docker-compose.yml file contains the right setting for working directory, i.e. -w

2017-05-07 12:18 UTC, chrberger commented on usecases/latest/calibration.projection/docker-compose.yml
> +    tool-camera-projection:
Here, the working directory path is missing (cf. above)

2017-05-07 12:18 UTC, chrberger commented on usecases/latest/test-camerareplay/configuration
> +core-tool-camera-replay.filepath = /opt/Videos/highway.avi
We should use relative paths preferably.

2017-05-18 12:07 UTC, bjornborg commented
Reqested changes are now done.

2017-05-18 18:29 UTC, chrberger commented
Thanks, looks fine

2017-05-18 18:29 UTC, chrberger approved these changes
@olbender ?

2017-05-19 19:22 UTC, merged