Use case for velodyne32
chalmers-revere/opendlv.core pull request #111
Opened 2017-10-02 07:43 UTC by HangYin2015

Add two "latest" use cases for velodyne32:
(1) calibrate.velodyne32: include odsupercomponent, proxy-velodyne32, and odcockpit to viualize point cloud of Velodyne 32 in real time
(2) recording.velodyne32: include odsupercomponent, proxy-velodyne32, and odrecorderh264 to log Velodyne 32 point cloud in headless mode

Both use cases have been successfully tested using odpcapreplay

2017-10-04 13:30 UTC, chrberger requested changes
This looks fine (just two minor things). Did you test this on SnowFox?

2017-10-04 13:30 UTC, chrberger commented on usecases/latest/velodyne32/calibrate.velodyne32/README.md
> +This folder provides the instructions for recording VLP-16 lidar data. A docker-compose file is provided to start all micro-services to decode VLP-16 packets, visualize them as 3D point cloud, and re
This README.md talks about VLP-16. I think this is a copy-and-paste error?

2017-10-04 13:30 UTC, chrberger commented on usecases/latest/velodyne32/recording.velodyne32/README.md
> +This folder provides the instructions for recording VLP-16 lidar data. A docker-compose file is provided to start all micro-services to decode VLP-16 packets, visualize them as 3D point cloud, and re
@HangYin2015 Same here?

2017-10-04 16:36 UTC, HangYin2015 commented
Thanks for the review! It is a stupid copy-and-paste error. Now both READMEs are updated. The use cases have not been tested on Snowfox yet. I will test it on Snowfox later.

2017-10-07 00:34 UTC, chrberger approved these changes

2017-10-07 00:34 UTC, merged