Gateway v6
chalmers-revere/opendlv.core pull request #61
Opened 2016-11-22 10:40 UTC by fgiaimo

Changes with the new dbc file: 

New CAN/ODVD Message:
EnergyLevels

Renamed CAN/ODVD Messages:
SteeringRequest => SteerRequest
ManualControl => ManualDriving
Propulsion => VehicleSpeed
VehicleState => VehicleDynamics

Renamed File: 
fh16gw.dbc => fh16gw_v6.dbc

Some of these changes can break the code on other branches that don't use the updated names for the CAN/ODVD messages (master builds, however).

2016-11-23 20:52 UTC, chrberger requested changes

2016-11-23 20:52 UTC, chrberger commented on resources/odvd/ODVDFH16Truck.odvd
> +message opendlv.proxy.reverefh16.ManualDriver [id = 191] {
As this PR contains renaming of messages, please make sure that you propagate this renaming to the higher-level repositories

2016-12-02 18:38 UTC, chrberger commented on resources/odvd/ODVDFH16Truck.odvd
> +message opendlv.proxy.reverefh16.ManualDriver [id = 191] {
@fgiaimo What is the status of this PR?

2016-12-05 08:23 UTC, fgiaimo commented on resources/odvd/ODVDFH16Truck.odvd
> +message opendlv.proxy.reverefh16.ManualDriver [id = 191] {
This PR is connected to https://github.com/chalmers-revere/opendlv/pull/119 . 
Approving both should fix the inter-dependencies among the two repositories.

2016-12-13 15:25 UTC, olbender approved these changes
This is fine. But we should soon move the Rhino related code to its own repository.

2016-12-14 12:10 UTC, fgiaimo commented on resources/odvd/ODVDFH16Truck.odvd
> +message opendlv.proxy.reverefh16.ManualDriver [id = 191] {
as support_for_dbc_v6 was merged in opendlv, we will need this PR merged as well to solve the naming changes

2016-12-14 13:17 UTC, chrberger approved these changes

2016-12-14 13:17 UTC, merged