Replace half float with uint16_t for CPC
chalmers-revere/opendlv.core pull request #68
Opened 2016-12-01 10:33 UTC by HangYin2015

2016-12-01 10:35 UTC, HangYin2015 commented
@chrberger Now the velodyne16 decoder for CPC uses uint16_t instead of half float. Could you please approve the PR? In order to visualize CPC in odcockpit after this change, EnvironmentViewer also needs to be changed to decode uint16_t distance values. I will make a separate PR in OpenDaVINCI very soon.

2016-12-01 12:00 UTC, chrberger approved these changes

2016-12-01 12:00 UTC, chrberger commented on code/core/system/proxy-velodyne16/src/velodyne16DecoderCPC.cpp
> +                    m_16Sensors[sensorID] = ntohs(firstByte * 256 + secondByte);
What is the physical unit that your data is based on when storing it in m_16Sensors[...]? Is it cm?

2016-12-01 12:01 UTC, chrberger requested changes
I withdraw my approval as I saw that you do a transformation in odcockpit.

2016-12-01 15:39 UTC, chrberger requested changes

2016-12-01 15:39 UTC, chrberger commented on usecases/stable/documentationcamera/recording.documentationcamera.realtime/Dockerfile
> +FROM seresearch/opendlv-core-on-opendavinci-ubuntu-16.04-complete:latest
A stable use case can't base on latest

2016-12-01 15:39 UTC, chrberger commented on usecases/stable/documentationcamera/calibrate.documentationcamera.realtime/Dockerfile
> +FROM seresearch/opendlv-core-on-opendavinci-ubuntu-16.04-complete:latest
A stable use case can't base on latest

2016-12-01 15:39 UTC, chrberger commented on usecases/stable/documentationcamera/recording.documentationcamera.realtime/odcockpit/Dockerfile
> +FROM seresearch/opendlv-core-on-opendavinci-ubuntu-16.04-complete:latest
A stable use case can't base on latest

2016-12-01 15:53 UTC, HangYin2015 commented on usecases/stable/documentationcamera/recording.documentationcamera.realtime/odcockpit/Dockerfile
> +FROM seresearch/opendlv-core-on-opendavinci-ubuntu-16.04-complete:latest
You are right. Use cases with the latests tag should not be in the stable folder. But opendlv.core evolves really fast and sometimes in order to quickly test a new version, I have to manually change the tag in the docker-compose file from a fixed release to latest. In this way, I do not have to frequently move use cases between the stable folder and latest folder.

Maybe the easiest way is to replace the “latest" tag in the docker-compose file with the latest version number? Now the number of use cases is growing and re-testing existing use cases with new releases becomes more time-consuming. What do you suggest?

2016-12-01 15:57 UTC, chrberger commented on usecases/stable/documentationcamera/recording.documentationcamera.realtime/odcockpit/Dockerfile
> +FROM seresearch/opendlv-core-on-opendavinci-ubuntu-16.04-complete:latest
In the stable folder, we only allow use cases that point to a fixed version that we know is working.

Everything else must reside in latest to avoid misunderstandings.

I am aware that we are currently changing many things related to camera/velodyne but we will settle this soon with the next testing round I suppose.

2016-12-01 16:08 UTC, HangYin2015 commented on usecases/stable/documentationcamera/recording.documentationcamera.realtime/odcockpit/Dockerfile
> +FROM seresearch/opendlv-core-on-opendavinci-ubuntu-16.04-complete:latest
OK. I agree that we should stick to the rules regarding stable and latest. In my opinion, it may not be a good idea to have different use cases of documentation camera or velodyne in stable and latest folders separately. So I prefer to directly update the tags in the docker-compose files in the stable folder and test if existing use cases still work with the new version. The problem is that when we first test some new features which are not supported by the official opendlv.core image yet, we have to change the docker-compose file by using the "latest" tag. When the official Docker image is released, we need to change "latest" further to the latest fixed version number and re-test. This process is also complicated.

2016-12-01 16:13 UTC, chrberger commented on usecases/stable/documentationcamera/recording.documentationcamera.realtime/odcockpit/Dockerfile
> +FROM seresearch/opendlv-core-on-opendavinci-ubuntu-16.04-complete:latest
Thanks for sticking to the agreed procedure.

2016-12-01 19:16 UTC, HangYin2015 commented on code/core/system/proxy-velodyne16/src/velodyne16DecoderCPC.cpp
> +                    m_16Sensors[sensorID] = ntohs(firstByte * 256 + secondByte);
It is cm.

2016-12-02 08:55 UTC, chrberger requested changes
Once we have v0.7.0 for OpenDLV.core, I will update the tag in stable/.

@HangYin2015, could you please test the stable use cases afterwards once more?

2016-12-02 08:55 UTC, chrberger commented on usecases/stable/documentationcamera/calibrate.documentationcamera.realtime/Dockerfile
>  FROM seresearch/opendlv-core-on-opendavinci-ubuntu-16.04-complete:latest
We still have :latest as tag here even though that this Dockerfile is residing in stable/.

According to our process, this is not allowed.

2016-12-02 08:55 UTC, chrberger commented on usecases/stable/documentationcamera/calibrate.documentationcamera/Dockerfile
> +FROM seresearch/opendlv-core-on-opendavinci-ubuntu-16.04-complete:v0.6.0
We need to update this once we have the next official release.

2016-12-02 08:55 UTC, chrberger commented on usecases/stable/documentationcamera/calibrate.documentationcamera/Dockerfile
> +FROM seresearch/opendlv-core-on-opendavinci-ubuntu-16.04-complete:v0.6.0
I will do this.

2016-12-02 08:55 UTC, chrberger commented on usecases/stable/documentationcamera/recording.documentationcamera.realtime/Dockerfile
> +FROM seresearch/opendlv-core-on-opendavinci-ubuntu-16.04-complete:v0.6.0
Same here.

2016-12-02 08:55 UTC, chrberger commented on usecases/stable/documentationcamera/recording.documentationcamera.realtime/fileserver/Dockerfile
>  FROM seresearch/opendlv-core-on-opendavinci-ubuntu-16.04-complete:latest
We still have :latest as tag here even though that this Dockerfile is residing in stable/.

According to our process, this is not allowed.

2016-12-02 08:55 UTC, chrberger commented on usecases/stable/documentationcamera/recording.documentationcamera.realtime/odcockpit/Dockerfile
>  FROM seresearch/opendlv-core-on-opendavinci-ubuntu-16.04-complete:latest
We still have :latest as tag here even though that this Dockerfile is residing in stable/.

According to our process, this is not allowed.

2016-12-02 08:55 UTC, chrberger commented on usecases/stable/documentationcamera/recording.documentationcamera/Dockerfile
> +FROM seresearch/opendlv-core-on-opendavinci-ubuntu-16.04-complete:v0.6.0
cf. above.

2016-12-02 08:55 UTC, chrberger commented on usecases/stable/replay.recording/Dockerfile
> +FROM seresearch/opendlv-core-on-opendavinci-ubuntu-16.04-complete:v0.6.0
cf. above.

2016-12-02 09:26 UTC, HangYin2015 commented on usecases/stable/documentationcamera/calibrate.documentationcamera/Dockerfile
> +FROM seresearch/opendlv-core-on-opendavinci-ubuntu-16.04-complete:v0.6.0
Yes. Once v0.7.0 is released. These use cases need to be tested again.

2016-12-02 17:46 UTC, chrberger approved these changes

2016-12-02 17:54 UTC, merged