2017 q1.refactoring.canfile.length
chalmers-revere/opendlv.core pull request #96
Opened 2017-02-23 15:41 UTC by fgiaimo

To be merged only right after https://github.com/se-research/OpenDaVINCI/pull/165

2017-02-24 19:21 UTC, chrberger approved these changes
Did you manually transform this file?

2017-02-27 07:38 UTC, fgiaimo commented
Yes. Whatever automated tool we had before, it will need to be updated. I may try to do something about it in the future.

2017-03-09 17:13 UTC, chrberger requested changes

2017-03-09 17:13 UTC, chrberger commented on resources/can/fh16mapping.can
> +CAN Message 0x101 wheelspeeds1 : 8 {
@fgiaimo Could you improve the language design slightly:

CAN Message 0x101 wheelspeeds1 : 8 {
-->
CANMessage 0x0101 wheelspeeds1 is 8 bytes {

2017-04-20 19:16 UTC, chrberger requested changes
This PR should be merged when the script to handle .dbc -> .can is ready and this branch has been verified on the truck again (using OpenDLV.rhino).

2017-07-06 14:18 UTC, merged